txt = input("Digite algo: ")
print(f'É da classe: {type(txt)}')
print('É completamente alfabético:', txt.isalpha())
print('É completamente númerico:', txt.isnumeric())
print('É completamente alfanúmerico:', txt.isalnum())
print('É completamente espaço: ', txt.isspace())
print('É completamente maiúsculo: ', txt.isupper())
print('É completamente minúsculo: ', txt.islower())
print('É capitalizado: ',txt.istitle())